name: Build Ordinal

on:
  push:
    paths:
    - 'ordinal/src/**'

  pull_request:
    paths: 
    - 'ordinal/src/**'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - name: Install dependencies
      run: |
        cd ./ordinal/src
        go get .
    - name: Build
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        cd ./ordinal/src
        if [[ "${{ matrix.platform }}" == "windows" ]]; then
          go build -v -o ../ordinal.exe .
        else
          go build -v -o ../ordinal .
        fi
    - uses: actions/upload-artifact@v3
      with:
        name: ordinal
        path: ordinal*
