# Variables
env:
  PROGRAM_NAME: thegame

# thegame workflow
name: Build thegame

on:
  push:
    paths:
      - 'thegame/src/**'
      
  pull_request:
    paths:
      - 'thegame/src/**'

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platform: [windows, linux]

    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x

    - name: Install dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: |
        if [[ "${{ matrix.platform }}" == "windows" ]]; then
          go build -v -o thegame.exe ./thegame
        else
          go build -v -o thegame ./thegame
        fi

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROGRAM_NAME }}-${{ matrix.platform }}
        path: ${{ env.PROGRAM_NAME }}*
