# Variables
env:
  PROGRAM_NAME: thegame

# thegame workflow
name: Build ${{ env.PROGRAM_NAME }}

on:
  push:
    paths:
      - '${{ env.PROGRAM_NAME }}/src/**'
      
  pull_request:
    paths:
      - '${{ env.PROGRAM_NAME }}/src/**'

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platform: [windows, linux]

    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x

    - name: Install dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: |
        if [[ "${{ matrix.platform }}" == "windows" ]]; then
          go build -v -o ${{ env.PROGRAM_NAME }}.exe ./${{ env.PROGRAM_NAME }}
        else
          go build -v -o ${{ env.PROGRAM_NAME }} ./${{ env.PROGRAM_NAME }}
        fi

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROGRAM_NAME }}-${{ matrix.platform }}
        path: ${{ env.PROGRAM_NAME }}*
