name: Build TheGame

on:
  push:
    paths:
    - 'thegame/src/**'

  pull_request:
    paths: 
    - 'thegame/src/**'

  workflow_dispatch:
    inputs:
      buildPlatform:
        description: 'Platform to build for (windows, linux)'
        required: true
        type: choice
        options:
        - windows
        - linux

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x

    - name: Install dependencies
      run: go get -v -t -d ./...

    - name: Build
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        if [[ "${{ github.event.inputs.buildPlatform }}" == "windows" ]]; then
          go build -v -o thegame.exe ./thegame
        else
          go build -v -o thegame ./thegame
        fi

    - uses: actions/upload-artifact@v2
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        name: thegame-${{ github.event.inputs.buildPlatform }}
        path: thegame*
